# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        description: "Formatting code"
        language: python
        language_version: 3.8.5
-   repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        description: "Styling guide enforcement"
        language: python
        language_version: 3.8.5
